### ISSUE TITLE
License tag

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OCIDE#2]
I suggest to add the License to the repo as documented in https://help.github.com/articles/adding-a-license-to-a-repository/ which would be "GitHub standard" and includes the license in this repo's metadata, too.
As soon as this is done https://github.com/LADSoft/OCIDE/tree/master/license can be removed.

**Comment by LADSoft** [comment]
hehehe...  I just recently caught on to the github standard licensing thing lol!   i'll look at ocide issues later this week or over the next weekend.

**Comment by GitMensch** [comment]
One question: https://github.com/LADSoft/OCIDE/blob/master/src/LICENSE.TXT does not apply to OCIDE at all and should therefore be removed from this repo, correct?
