### ISSUE TITLE
Inoperative Watch<-Debug on Windows-7-64 bit 

### ISSUE THREAD

**Issue by svmizin** [LADSoft/OCIDE#29]
Dear OCC creators.
Debug->Watch is absolutely disabled on my Windows-7-64 comp for any projects and any variables (global and locals) for both recent OCC versions : 6.0. 41.1 & 6.0.37.1 
I have some pause in programming, and when i started new project, i revealed that Watcher of debugger is absolutely Inoperative. Look at attached on-screen. When i am truing insert  ANY variable (global or local) in ANY watcher-window - i always get error message :"Undefined symbol".  Such situation i have now for ALL  right projects for Orange C:  for sample-projects , involved in OCC Installation Pack as far as all my own projects.
Also i attach one my own frame-project.
I will be glad and grateful for any your help.

![No_watch](https://user-images.githubusercontent.com/35298943/62711677-27168900-ba02-11e9-8a27-28466b94e84d.jpg)

**Comment by LADSoft** [comment]
I'm closing this for now; reopen if it becomes an issue again.
