### ISSUE TITLE
FR for ocide: File->Close all

### ISSUE THREAD

**Issue by GitMensch** [LADSoft/OCIDE#47]
It would be nice to be able to close all files currently open in the editor (not the cwa/project files).
Especially when searching for something or investigate definitions (which will work again LADSoft/OrangeC#108) one may open many editor windows. I currently found no other way to close all than pressing [ALT]+[F]+[C] multiple times (as this workaround exists I'd consider this as very low priority, although I guess the implementation, maybe with a popup window asking if this really should be done [only if more than one file is open] would be easy to implement).

**Comment by LADSoft** [comment]
close file closes an editor window whereas close on the window menu will close ANY window.   Close all closes all windows not just files...   but I agree save all doesn't fit on the window menu...
